<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PriceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('prices')->insert(
            [
                [
                    'title'        => 'Щит навесной, без подключения',
                    'installation' => 560,
                    'dismantling'  => 340,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Щит встраиваемый, без подключения',
                    'installation' => 800,
                    'dismantling'  => 450,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Штробление под щит (ниша) в бетоне (500x300x200мм)',
                    'installation' => 3000,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Штробление под щит (ниша) в кирпиче (500x300x200мм)',
                    'installation' => 1800,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Электросчетчик однофазный',
                    'installation' => 600,
                    'dismantling'  => 250,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Электросчетчик трехфазный',
                    'installation' => 1100,
                    'dismantling'  => 450,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Однополюсный автомат, УЗО',
                    'installation' => 250,
                    'dismantling'  => 100,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Двухполюсный автомат',
                    'installation' => 350,
                    'dismantling'  => 150,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Трехполюсный автомат',
                    'installation' => 600,
                    'dismantling'  => 350,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Пакетник',
                    'installation' => 350,
                    'dismantling'  => 200,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Установка DIN рейки',
                    'installation' => 200,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Установка шин N, PE',
                    'installation' => 200,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Перекоммутация старого щита',
                    'installation' => 2000,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Подключение силовой линии 220В',
                    'installation' => 350,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Подключение силовой линии 380В',
                    'installation' => 500,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Открытая электропроводка',
                    'installation' => null,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => null,
                ],
                [
                    'title'        => 'По бетону, кирпичу (по стенам)',
                    'installation' => 100,
                    'dismantling'  => 15,
                    'from'         => null,
                    'unit'         => 'пог.м',
                ],
                [
                    'title'        => 'Укладка кабеля по плинтусу, наличнику',
                    'installation' => 30,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'пог.м',
                ],
                [
                    'title'        => 'Укладка кабеля в кабель-канале',
                    'installation' => 30,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'пог.м',
                ],
                [
                    'title'        => 'Плинтус',
                    'installation' => 100,
                    'dismantling'  => 20,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Кабель канал',
                    'installation' => 100,
                    'dismantling'  => 20,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Розетка, выключатель',
                    'installation' => 800,
                    'dismantling'  => 450,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Розетка TV, интернет',
                    'installation' => 800,
                    'dismantling'  => 450,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Прокладка кабеля по потолку',
                    'installation' => 60,
                    'dismantling'  => 20,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Прокладка кабеля в гофре по потолку',
                    'installation' => 80,
                    'dismantling'  => 20,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Распределительная коробка',
                    'installation' => 80,
                    'dismantling'  => 20,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Скрытая электропроводка',
                    'installation' => null,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => null,
                ],
                [
                    'title'        => 'Устройство штробы под электропроводку в бетоне',
                    'installation' => 450,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'пог.м',
                ],
                [
                    'title'        => 'Устройство штробы под электропроводку в кирпиче',
                    'installation' => 350,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'пог.м',
                ],
                [
                    'title'        => 'Устройство штробы под электропроводку в штукатурке',
                    'installation' => 280,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'пог.м',
                ],
                [
                    'title'        => 'Укладка кабеля в штробе',
                    'installation' => 30,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'пог.м',
                ],
                [
                    'title'        => 'Укладка кабеля в гофре по штробам, в стяжку',
                    'installation' => 50,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'пог.м',
                ],
                [
                    'title'        => 'Оштукатуривание штробы',
                    'installation' => 40,
                    'dismantling'  => null,
                    'from'         => 'от',
                    'unit'         => 'пог.м',
                ],
                [
                    'title'        => 'Устройство гнезда для подрозетника в бетоне',
                    'installation' => 350,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Устройство гнезда для подрозетника в кирпиче',
                    'installation' => 250,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Устройство гнезда для подрозетника в пеноблоке',
                    'installation' => 100,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Устройство гнезда для подразетника в ГКЛ',
                    'installation' => 50,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Блок выключателей, розеток',
                    'installation' => 100,
                    'dismantling'  => 50,
                    'from'         => 'от',
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Розетка, выключатель',
                    'installation' => 50,
                    'dismantling'  => 30,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Розетка TV, интернета',
                    'installation' => 50,
                    'dismantling'  => 30,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Осветительные приборы',
                    'installation' => null,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => null,
                ],
                [
                    'title'        => 'Светильник и бра',
                    'installation' => 450,
                    'dismantling'  => 250,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Люстра',
                    'installation' => 700,
                    'dismantling'  => 350,
                    'from'         => 'от',
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Сборка люстры',
                    'installation' => 300,
                    'dismantling'  => null,
                    'from'         => 'от',
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Установка крюка для люстры',
                    'installation' => 200,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Установка планки для люстры',
                    'installation' => 250,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Установка встроенных светильников в ГКЛ',
                    'installation' => 200,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Установка встроенных светильников в реечный потолок',
                    'installation' => 250,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Установка встроенных светильников в подвесном потолке «Амстронг»',
                    'installation' => 200,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Установка светодиодной ленты',
                    'installation' => 450,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Установка диммера',
                    'installation' => 800,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Замена патрона',
                    'installation' => 250,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Замена ламп',
                    'installation' => 50,
                    'dismantling'  => null,
                    'from'         => 'от',
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Ремонт осветительных приборов',
                    'installation' => 400,
                    'dismantling'  => null,
                    'from'         => 'от',
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Замена дросселя галогенной лампы',
                    'installation' => 500,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Установка эл/звонка без кнопки',
                    'installation' => 360,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Установка кнопки эл/звонка',
                    'installation' => 150,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Подключение бытовой техники по электрике',
                    'installation' => null,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => null,
                ],
                [
                    'title'        => 'Стиральная машина',
                    'installation' => 800,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Посудомоечная машина',
                    'installation' => 800,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Накопительный бойлер',
                    'installation' => 800,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Насос, повышающий давление',
                    'installation' => 800,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Измельчитель отходов',
                    'installation' => 800,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Электроплита',
                    'installation' => 800,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Варочная панель',
                    'installation' => 560,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Духовой шкаф',
                    'installation' => 800,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Вытяжка',
                    'installation' => 800,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'шт',
                ],
                [
                    'title'        => 'Особые условия',
                    'installation' => null,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => null,
                ],
                [
                    'title'        => 'Коэффициент стесненности',
                    'installation' => 20,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => '%',
                ],
                [
                    'title'        => 'Определение неисправности, прозвонка кабеля',
                    'installation' => 800,
                    'dismantling'  => null,
                    'from'         => null,
                    'unit'         => 'час',
                ],
                [
                    'title'        => 'Наценка на работы после неквалифицированного вмешательства',
                    'installation' => 20,
                    'dismantling'  => null,
                    'from'         => 'от',
                    'unit'         => '%',
                ],
                [
                    'title'        => 'Льгота на работу для пенсионеров',
                    'installation' => 5,
                    'dismantling'  => null,
                    'from'         => 'от',
                    'unit'         => '%',
                ]
            ]
        );
    }
}
